import { Link } from 'react-router-dom'

export default function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-8">

      <div className="text-center space-y-2 pb-6 border-b border-slate-200">
        <div className="text-4xl">⚠️</div>
        <h1 className="text-3xl font-bold text-slate-900">Disclaimer</h1>
        <p className="text-slate-500 text-sm">
          Last updated: {new Date().toLocaleDateString('en-US', {
            year: 'numeric', month: 'long', day: 'numeric'
          })}
        </p>
      </div>

      {/* Main Warning Box */}
      <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-6 space-y-3">
        <h2 className="text-xl font-black text-amber-900 flex items-center gap-2">
          ⚠️ Educational Tool — Not Legal Advice
        </h2>
        <p className="text-amber-800 text-sm leading-relaxed">
          BarPrep AI is an <strong>educational study tool</strong> designed
          to assist individuals preparing for bar examinations. It is
          <strong> NOT </strong> a law firm, legal service, or licensed
          bar preparation course. Nothing on this platform constitutes
          legal advice of any kind.
        </p>
      </div>

      <div className="space-y-6">

        {[
          {
            icon: '🤖',
            title: 'AI-Generated Content',
            content: `The questions, explanations, study plans, and feedback
              provided by BarPrep AI are generated by artificial intelligence.
              While we strive for accuracy, AI-generated content may contain
              errors, outdated information, or incomplete analysis. Always
              verify important legal rules and principles with official
              bar preparation materials, law textbooks, and your jurisdiction's
              official resources.`,
          },
          {
            icon: '📊',
            title: 'No Guarantee of Results',
            content: `Using BarPrep AI does not guarantee that you will pass
              the bar examination. Bar exam performance depends on many
              factors including individual effort, preparation quality,
              and exam conditions. Our platform is designed to supplement
              your preparation, not replace comprehensive study programs.`,
          },
          {
            icon: '⚖️',
            title: 'Not Affiliated with NCBE',
            content: `BarPrep AI is not affiliated with, endorsed by, or
              connected to the National Conference of Bar Examiners (NCBE),
              any state bar association, or any official bar examination
              authority. The Multistate Bar Examination (MBE), Multistate
              Essay Examination (MEE), and other bar exam components are
              administered by official bodies independent of BarPrep AI.`,
          },
          {
            icon: '📚',
            title: 'Supplement, Not Replace',
            content: `BarPrep AI is intended to supplement — not replace —
              accredited bar preparation courses, law school education,
              and official study materials. We strongly recommend using
              BarPrep AI alongside comprehensive, accredited bar prep
              programs such as Barbri, Themis, or similar courses.`,
          },
          {
            icon: '🔄',
            title: 'Content Accuracy & Currency',
            content: `Laws, rules, and legal standards change over time.
              While we make reasonable efforts to keep our content current,
              we cannot guarantee that all information reflects the most
              recent legal developments. Always check the most current
              version of applicable laws and rules.`,
          },
          {
            icon: '💻',
            title: 'Technology Limitations',
            content: `As an AI-powered platform, BarPrep AI may experience
              technical issues, downtime, or errors in AI responses.
              We are not liable for any interruptions in service or
              inaccurate AI outputs that may affect your study preparation.`,
          },
        ].map(({ icon, title, content }) => (
          <div key={title} className="space-y-2">
            <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <span>{icon}</span> {title}
            </h2>
            <p className="text-slate-600 text-sm leading-relaxed">{content}</p>
          </div>
        ))}

      </div>

      {/* Contact */}
      <div className="bg-slate-50 border border-slate-200
                      rounded-xl p-5 space-y-2">
        <h3 className="font-bold text-slate-800">Questions?</h3>
        <p className="text-sm text-slate-600">
          If you have questions about this disclaimer or our service,
          please{' '}
          <Link to="/contact"
            className="text-blue-600 hover:underline font-medium">
            contact us
          </Link>
          {' '}or email{' '}
          <a href="mailto:legal@barprepai.com"
            className="text-blue-600 hover:underline">
            legal@barprepai.com
          </a>
        </p>
      </div>

      <div className="border-t border-slate-200 pt-6 flex flex-wrap gap-3">
        <Link to="/privacy"
          className="text-sm text-blue-600 hover:underline font-medium">
          Privacy Policy →
        </Link>
        <Link to="/terms"
          className="text-sm text-blue-600 hover:underline font-medium">
          Terms of Service →
        </Link>
        <Link to="/cookies"
          className="text-sm text-blue-600 hover:underline font-medium">
          Cookie Policy →
        </Link>
      </div>

    </div>
  )
}
