import { useState, useCallback, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'

// ── FAQ Data ──────────────────────────────────────────────────────────────────
const FAQS = [
  {
    id:       'about',
    category: '🤖 About BarPrep AI',
    questions: [
      {
        q: 'What is BarPrep AI?',
        a: 'BarPrep AI is an AI-powered bar exam preparation platform. It provides an AI coach for legal questions, mock exam practice with instant grading, personalized study plans, video tutorials, blog articles, and assignment analysis — all powered by artificial intelligence.',
      },
      {
        q: 'Is BarPrep AI affiliated with the NCBE or any bar association?',
        a: 'No. BarPrep AI is an independent educational tool and is not affiliated with, endorsed by, or connected to the National Conference of Bar Examiners (NCBE), any state bar association, or any official bar examination authority.',
      },
      {
        q: 'What bar exams does BarPrep AI cover?',
        a: 'BarPrep AI primarily focuses on the Uniform Bar Exam (UBE) content including all 10 MBE subjects: Constitutional Law, Contracts, Torts, Criminal Law, Civil Procedure, Evidence, Real Property, Business Associations, Family Law, and Wills & Trusts — as well as MEE essay topics.',
      },
      {
        q: 'Can BarPrep AI guarantee I will pass the bar exam?',
        a: 'No. We cannot guarantee bar exam results. BarPrep AI is a study supplement designed to improve your preparation. Passing depends on many factors including individual effort, baseline knowledge, and exam conditions. We strongly recommend using BarPrep AI alongside accredited bar prep courses.',
      },
    ],
  },
  {
    id:       'blog',
    category: '📰 Blog & AI Content',
    questions: [
      {
        q: 'Is the blog content written by real lawyers?',
        a: 'No. Our blog content is generated automatically by AI using live bar prep data feeds and Pollinations AI. Blog articles are for general educational purposes only and have not been reviewed by licensed attorneys. Always verify blog content with official sources.',
      },
      {
        q: 'How often is new blog content published?',
        a: 'New blog posts are generated daily based on live bar prep feeds and trending legal topics. Our admin team reviews and approves posts before they are published to the blog.',
      },
      {
        q: 'Can I trust the information in blog posts?',
        a: 'Blog posts are AI-generated and intended for educational purposes only. While we aim for accuracy, AI can make mistakes. Always cross-reference important legal information with official bar prep materials, law textbooks, and your jurisdiction\'s official resources.',
      },
      {
        q: 'Are blog images AI-generated?',
        a: 'Yes. Blog cover images are generated by Pollinations AI based on the article topic. These are original AI-generated images created for each post.',
      },
    ],
  },
  {
    id:       'privacy',
    category: '🔒 Privacy & Data',
    questions: [
      {
        q: 'Is my data safe?',
        a: 'Yes. We use Supabase, an enterprise-grade database with encryption in transit and at rest. Your password is never stored in plain text. Row-level security ensures only you can access your study data.',
      },
      {
        q: 'Does BarPrep AI sell my data?',
        a: 'Absolutely not. We do not sell, rent, or trade your personal data to any third parties. See our Privacy Policy for full details on how we handle your data.',
      },
      {
        q: 'How do I delete my account?',
        a: 'You can request account deletion by contacting us at privacy@barprepai.com. We will delete your account and all associated data within 30 days of your request.',
      },
      {
        q: 'Is my chat data used to train AI models?',
        a: 'Your conversations are processed by AI providers to generate responses. We do not use your personal study data to train our own AI models. Third-party AI providers have their own data policies.',
      },
    ],
  },
  {
    id:       'using',
    category: '📝 Using the App',
    questions: [
      {
        q: 'How accurate is the AI grading on mock exams?',
        a: 'The AI grading is designed to closely mirror bar exam standards, but it is not perfect. AI assessments are meant to give you directional feedback and help identify weak areas. Treat AI grades as learning tools rather than definitive assessments.',
      },
      {
        q: 'How does the personalized study plan work?',
        a: 'Enter your bar exam date and the AI analyzes your mock exam history, weak topics, and accuracy rates to build a day-by-day study schedule. The plan prioritizes your weakest topics and includes regular reviews and mock exam simulation days.',
      },
      {
        q: 'What file types can I upload for assignment analysis?',
        a: 'You can upload TXT, PDF, and DOC/DOCX files up to 5MB. You can also paste text directly into the text area. The AI will analyze your essay, memo, brief, or practice answer and provide detailed feedback.',
      },
      {
        q: 'How many mock exam questions can I practice?',
        a: 'There is no limit. You can generate as many practice questions as you want across all 10 MBE topics. Each question is AI-generated and unique.',
      },
      {
        q: 'Can I use BarPrep AI on my phone?',
        a: 'Yes. BarPrep AI is fully responsive and works on smartphones, tablets, and desktop computers. We recommend a tablet or desktop for longer study sessions.',
      },
    ],
  },
  {
    id:       'billing',
    category: '💰 Account & Billing',
    questions: [
      {
        q: 'Is BarPrep AI free to use?',
        a: 'BarPrep AI offers a free tier with access to core features. Contact us for information about premium plans with additional features such as unlimited AI coaching sessions and advanced analytics.',
      },
      {
        q: 'How do I reset my password?',
        a: 'Click "Forgot Password" on the login page and enter your email address. You will receive a password reset link within a few minutes. Check your spam folder if you do not see it.',
      },
      {
        q: 'Can I use one account on multiple devices?',
        a: 'Yes. Your account works across all your devices. Your study progress, chat history, and exam attempts are synced via our cloud database.',
      },
    ],
  },
  {
    id:       'technical',
    category: '🛠️ Technical',
    questions: [
      {
        q: 'What browsers are supported?',
        a: 'BarPrep AI works best on modern browsers including Chrome, Firefox, Safari, and Edge. We recommend keeping your browser updated to the latest version.',
      },
      {
        q: 'What do I do if the AI is not responding?',
        a: 'First, check your internet connection. If the issue persists, try refreshing the page. If you continue to experience problems, please contact our support team with details about the issue.',
      },
      {
        q: 'Is my data backed up?',
        a: 'Yes. Your data is stored in Supabase cloud infrastructure with automatic backups. However, we recommend periodically exporting important study notes for your own records.',
      },
    ],
  },
]

// ── Highlight search term in text ─────────────────────────────────────────────
function Highlight({ text, query }) {
  if (!query.trim()) return <>{text}</>
  const parts = text.split(new RegExp(`(${query})`, 'gi'))
  return (
    <>
      {parts.map((part, i) =>
        part.toLowerCase() === query.toLowerCase() ? (
          <mark
            key={i}
            className="bg-yellow-200 text-yellow-900 rounded px-0.5"
          >
            {part}
          </mark>
        ) : (
          <span key={i}>{part}</span>
        )
      )}
    </>
  )
}

// ── Accordion item ─────────────────────────────────────────────────────────────
function AccordionItem({ q, a, isOpen, onToggle, searchQuery, itemId }) {
  const contentRef = useRef(null)

  return (
    <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <button
        onClick={onToggle}
        aria-expanded={isOpen}
        aria-controls={`faq-answer-${itemId}`}
        id={`faq-btn-${itemId}`}
        className="w-full flex items-center justify-between
                   p-4 text-left gap-4 hover:bg-slate-50
                   transition-colors"
      >
        <span className="text-sm font-semibold text-slate-900">
          <Highlight text={q} query={searchQuery} />
        </span>
        <span
          className={`
            text-slate-400 text-xs shrink-0 transition-transform duration-200
            ${isOpen ? 'rotate-180' : ''}
          `}
        >
          ▼
        </span>
      </button>

      {/* Animated content */}
      <div
        id={`faq-answer-${itemId}`}
        role="region"
        aria-labelledby={`faq-btn-${itemId}`}
        ref={contentRef}
        className={`
          overflow-hidden transition-all duration-300 ease-in-out
          ${isOpen ? 'max-h-[500px] opacity-100' : 'max-h-0 opacity-0'}
        `}
      >
        <div className="px-4 pb-4 border-t border-slate-100 pt-3 bg-slate-50/50">
          <p className="text-sm text-slate-600 leading-relaxed">
            <Highlight text={a} query={searchQuery} />
          </p>
        </div>
      </div>
    </div>
  )
}

// ── Main component ────────────────────────────────────────────────────────────
export default function FAQ() {
  const [openItems,    setOpenItems]    = useState(new Set())
  const [searchQuery,  setSearchQuery]  = useState('')
  const searchRef = useRef(null)

  // SEO
  useEffect(() => {
    document.title = 'FAQ — BarPrep AI'
  }, [])

  // ── Toggle single item ─────────────────────────────────────────────────────
  const toggle = useCallback((key) => {
    setOpenItems(prev => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }, [])

  // ── Open all matched items on search ──────────────────────────────────────
  useEffect(() => {
    if (!searchQuery.trim()) {
      setOpenItems(new Set())
      return
    }
    const matched = new Set()
    FAQS.forEach(cat => {
      cat.questions.forEach(({ q, a }) => {
        const key = `${cat.id}-${q}`
        if (
          q.toLowerCase().includes(searchQuery.toLowerCase()) ||
          a.toLowerCase().includes(searchQuery.toLowerCase())
        ) {
          matched.add(key)
        }
      })
    })
    setOpenItems(matched)
  }, [searchQuery])

  // ── Filter categories ──────────────────────────────────────────────────────
  const filtered = FAQS.map(cat => ({
    ...cat,
    questions: cat.questions.filter(
      ({ q, a }) =>
        !searchQuery.trim() ||
        q.toLowerCase().includes(searchQuery.toLowerCase()) ||
        a.toLowerCase().includes(searchQuery.toLowerCase())
    ),
  })).filter(cat => cat.questions.length > 0)

  const totalResults = filtered.reduce((sum, c) => sum + c.questions.length, 0)

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-8">

      {/* ── Header ── */}
      <div className="text-center space-y-4">
        <div className="text-4xl">❓</div>
        <h1 className="text-3xl font-black text-slate-900">
          Frequently Asked Questions
        </h1>
        <p className="text-slate-500 text-sm max-w-xl mx-auto">
          Can't find what you're looking for?{' '}
          <Link to="/contact" className="text-blue-600 hover:underline font-medium">
            Contact us
          </Link>
        </p>

        {/* Search */}
        <div className="max-w-md mx-auto relative">
          <span className="absolute left-3 top-1/2 -translate-y-1/2
                           text-slate-400 text-sm pointer-events-none">
            🔍
          </span>
          <input
            ref={searchRef}
            type="text"
            placeholder="Search questions..."
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className="w-full border border-slate-200 rounded-xl pl-9 pr-10
                       py-2.5 text-sm focus:outline-none focus:border-blue-500
                       transition-colors bg-white"
          />
          {searchQuery && (
            <button
              onClick={() => {
                setSearchQuery('')
                searchRef.current?.focus()
              }}
              className="absolute right-3 top-1/2 -translate-y-1/2
                         text-slate-400 hover:text-slate-600 transition-colors"
            >
              ✕
            </button>
          )}
        </div>

        {/* Search results count */}
        {searchQuery && (
          <p className="text-xs text-slate-500">
            {totalResults} result{totalResults !== 1 ? 's' : ''} for
            "{searchQuery}"
          </p>
        )}
      </div>

      {/* ── Jump links (hidden during search) ── */}
      {!searchQuery && (
        <nav className="bg-slate-50 border border-slate-200 rounded-2xl p-4">
          <p className="text-xs font-bold text-slate-500 uppercase
                        tracking-wider mb-3">
            Jump to Category
          </p>
          <div className="flex flex-wrap gap-2">
            {FAQS.map(({ id, category }) => (
              <a
                key={id}
                href={`#faq-${id}`}
                className="text-xs text-blue-600 hover:text-blue-800
                           hover:underline transition-colors px-2 py-1
                           bg-white border border-slate-200 rounded-lg"
              >
                {category}
              </a>
            ))}
          </div>
        </nav>
      )}

      {/* ── FAQ content ── */}
      {filtered.length === 0 ? (
        <div className="text-center py-12 space-y-3">
          <p className="text-4xl">🔍</p>
          <p className="text-slate-600 font-medium">
            No results for "{searchQuery}"
          </p>
          <p className="text-slate-500 text-sm">
            Try different keywords or ask us directly.
          </p>
          <Link
            to="/contact"
            className="inline-block text-blue-600 hover:underline
                       text-sm font-medium"
          >
            Ask us directly →
          </Link>
        </div>
      ) : (
        <div className="space-y-10">
          {filtered.map(cat => (
            <div key={cat.id} id={`faq-${cat.id}`} className="scroll-mt-20">
              <div className="flex items-center justify-between mb-3">
                <h2 className="text-base font-bold text-slate-800 uppercase
                               tracking-wide">
                  {cat.category}
                </h2>
                <span className="text-xs text-slate-400">
                  {cat.questions.length} question
                  {cat.questions.length !== 1 ? 's' : ''}
                </span>
              </div>

              <div className="space-y-2">
                {cat.questions.map(({ q, a }) => {
                  const key    = `${cat.id}-${q}`
                  const isOpen = openItems.has(key)
                  return (
                    <AccordionItem
                      key={key}
                      itemId={key.replace(/\s+/g, '-')}
                      q={q}
                      a={a}
                      isOpen={isOpen}
                      onToggle={() => toggle(key)}
                      searchQuery={searchQuery}
                    />
                  )
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── CTA ── */}
      <div className="bg-blue-50 border border-blue-200 rounded-2xl
                      p-6 text-center space-y-3">
        <p className="text-lg font-bold text-blue-900">
          Still have questions?
        </p>
        <p className="text-sm text-blue-700">
          Our support team typically responds within 24 hours.
        </p>
        <div className="flex justify-center gap-3 flex-wrap">
          <Link
            to="/contact"
            className="px-8 py-2.5 bg-blue-600 text-white text-sm
                       font-bold rounded-xl hover:bg-blue-700 transition-colors"
          >
            Contact Support →
          </Link>
          <Link
            to="/blog"
            className="px-8 py-2.5 border border-blue-200 text-blue-700
                       text-sm font-bold rounded-xl hover:bg-blue-100
                       transition-colors"
          >
            📰 Read the Blog
          </Link>
        </div>
      </div>

    </div>
  )
}
