import { useState } from 'react'
import { apiClient } from '../api/client'
import LoadingSpinner from '../components/LoadingSpinner'
import ReactMarkdown from 'react-markdown'

const TOPICS = [
  'Constitutional Law',
  'Contracts',
  'Torts',
  'Criminal Law',
  'Civil Procedure',
  'Evidence',
  'Real Property',
  'Business Associations',
  'Family Law',
  'Wills & Trusts',
]

// Helper to strip any injected ads or promotional text
function cleanAIResponse(text) {
  if (!text) return ''
  
  // Remove common Pollinations promotional injections
  const adPatterns = [
    /pollinations\.ai[^\n]*/gi,
    /generated by[^\n]*/gi,
    /powered by[^\n]*/gi,
    /\[.*?pollinations.*?\]/gi,
    /https?:\/\/.*?pollinations[^\s]*/gi,
    /image by[^\n]*/gi,
    /via pollinations[^\n]*/gi,
  ]
  
  let cleaned = text
  adPatterns.forEach(pattern => {
    cleaned = cleaned.replace(pattern, '')
  })
  
  return cleaned.trim()
}

export default function MockExam() {
  const [topic, setTopic]       = useState(TOPICS[0])
  const [question, setQuestion] = useState(null)
  const [answer, setAnswer]     = useState('')
  const [feedback, setFeedback] = useState(null)
  const [loading, setLoading]   = useState(false)
  const [phase, setPhase]       = useState('select')
  const [error, setError]       = useState('')

  const generateQuestion = async () => {
    setLoading(true)
    setFeedback(null)
    setAnswer('')
    setError('')

    try {
      const prompt = `You are a bar exam question generator.
Generate ONE realistic MBE-style multiple choice question about ${topic}.

Format your response EXACTLY like this with no extra text:

QUESTION: [Write the full question scenario here]

A) [First answer option]
B) [Second answer option]
C) [Third answer option]
D) [Fourth answer option]

Do NOT reveal the correct answer.
Do NOT add any commentary before or after.
Just the question and four options exactly as formatted above.`

      const res = await apiClient.chat(prompt)
      const cleaned = cleanAIResponse(res.data.reply)
      setQuestion(cleaned)
      setPhase('question')
    } catch (err) {
      setError('Failed to generate question. Please try again.')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  const submitAnswer = async () => {
    if (!answer) return
    setLoading(true)
    setError('')

    try {
      const prompt = `You are a bar exam coach evaluating a student answer.

The student was asked this question:
${question}

The student selected: Option ${answer}

Your task:
1. State clearly if they are CORRECT or INCORRECT
2. Reveal the correct answer with the letter
3. Explain WHY the correct answer is right using step-by-step legal reasoning
4. If wrong explain why their choice was incorrect
5. End with one encouraging sentence

Be thorough but concise. Use clear legal terminology.
Do NOT add any promotional text or links.`

      const res = await apiClient.chat(prompt)
      const cleaned = cleanAIResponse(res.data.reply)
      setFeedback(cleaned)
      setPhase('feedback')
    } catch (err) {
      setError('Failed to evaluate answer. Please try again.')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  const reset = () => {
    setQuestion(null)
    setAnswer('')
    setFeedback(null)
    setPhase('select')
    setError('')
  }

  return (
    <div className="space-y-6 max-w-3xl mx-auto px-4 sm:px-6 lg:px-0">

      {/* Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900">
          Mock Exam
        </h1>
        <p className="text-slate-500 mt-1 text-sm sm:text-base">
          Practice with AI-generated bar exam questions.
          Get instant feedback and step-by-step explanations.
        </p>
      </div>

      {/* Error Banner */}
      {error && (
        <div className="p-4 bg-red-50 border border-red-200 
                        rounded-lg text-red-700 text-sm">
          ❌ {error}
        </div>
      )}

      {/* Phase: Select Topic */}
      {phase === 'select' && (
        <div className="card space-y-4">
          <h2 className="text-lg font-semibold text-slate-900">
            Select A Topic
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 
                          md:grid-cols-3 gap-2">
            {TOPICS.map((t) => (
              <button
                key={t}
                onClick={() => setTopic(t)}
                className={`p-3 rounded-lg text-sm font-medium 
                  text-left transition-colors duration-200 border
                  min-h-[44px]
                  ${topic === t
                    ? 'bg-blue-50 border-blue-300 text-blue-700'
                    : 'bg-white border-slate-200 text-slate-600 hover:border-slate-300'
                  }`}
              >
                {t}
              </button>
            ))}
          </div>

          <button
            onClick={generateQuestion}
            disabled={loading}
            className="btn-primary w-full min-h-[44px]"
          >
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <LoadingSpinner size="sm" />
                Generating Question...
              </span>
            ) : (
              `Generate ${topic} Question →`
            )}
          </button>
        </div>
      )}

      {/* Phase: Answer Question */}
      {phase === 'question' && question && (
        <div className="card space-y-5">

          {/* Topic Badge + Back */}
          <div className="flex items-center justify-between 
                          flex-wrap gap-2">
            <span className="badge bg-blue-100 text-blue-700 
                             px-3 py-1 text-xs font-semibold">
              {topic}
            </span>
            <button
              onClick={reset}
              className="text-sm text-slate-500 hover:text-slate-700 
                         transition-colors"
            >
              ← Change Topic
            </button>
          </div>

          {/* Question Text */}
          <div className="prose prose-slate max-w-none 
                          text-sm sm:text-base leading-relaxed">
            <ReactMarkdown>{question}</ReactMarkdown>
          </div>

          {/* Answer Selection */}
          <div className="space-y-3">
            <p className="text-sm font-semibold text-slate-700">
              Select Your Answer:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {['A', 'B', 'C', 'D'].map((letter) => (
                <button
                  key={letter}
                  onClick={() => setAnswer(letter)}
                  className={`p-3 rounded-lg text-sm font-semibold
                    border-2 transition-all duration-200 min-h-[48px]
                    flex items-center justify-center gap-2
                    ${answer === letter
                      ? 'bg-blue-600 border-blue-600 text-white shadow-md'
                      : 'bg-white border-slate-200 text-slate-700 hover:border-blue-300 hover:bg-blue-50'
                    }`}
                >
                  <span className={`w-6 h-6 rounded-full border-2 
                    flex items-center justify-center text-xs font-bold
                    ${answer === letter
                      ? 'border-white bg-white text-blue-600'
                      : 'border-slate-300 text-slate-500'
                    }`}>
                    {letter}
                  </span>
                  Option {letter}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={submitAnswer}
            disabled={!answer || loading}
            className="btn-primary w-full min-h-[48px]"
          >
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <LoadingSpinner size="sm" />
                Evaluating Your Answer...
              </span>
            ) : (
              answer
                ? `Submit Answer ${answer} →`
                : 'Select An Answer First'
            )}
          </button>
        </div>
      )}

      {/* Phase: Feedback */}
      {phase === 'feedback' && feedback && (
        <div className="space-y-4">
          <div className="card">
            <div className="flex items-center gap-2 mb-4">
              <span className="badge bg-blue-100 text-blue-700 
                               px-3 py-1 text-xs font-semibold">
                {topic}
              </span>
              <h2 className="text-lg font-semibold text-slate-900">
                AI Feedback
              </h2>
            </div>
            <div className="prose prose-slate max-w-none 
                            text-sm sm:text-base leading-relaxed">
              <ReactMarkdown>{feedback}</ReactMarkdown>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={generateQuestion}
              className="btn-primary flex-1 min-h-[48px]"
              disabled={loading}
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <LoadingSpinner size="sm" />
                  Loading...
                </span>
              ) : (
                'Next Question →'
              )}
            </button>
            <button
              onClick={reset}
              className="btn-secondary flex-1 min-h-[48px]"
            >
              Change Topic
            </button>
          </div>
        </div>
      )}

    </div>
  )
}
