import axios from 'axios'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL      = import.meta.env.VITE_SUPABASE_URL
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY
const BACKEND_URL       = import.meta.env.VITE_BACKEND_URL
const FUNCTIONS_URL     = `${SUPABASE_URL}/functions/v1`

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

// ── Supabase Edge Functions API ───────────────────────────────────────────────
const api = axios.create({
  baseURL: FUNCTIONS_URL,
  timeout: 60000,
  headers: {
    'Content-Type': 'application/json',
    'apikey':       SUPABASE_ANON_KEY,
  },
})

// ── Attach session token on every request ─────────────────────────────────────
api.interceptors.request.use(async (config) => {
  const { data: { session } } = await supabase.auth.getSession()
  config.headers.Authorization = `Bearer ${session?.access_token || SUPABASE_ANON_KEY}`
  return config
})

// ── Request logging (dev only) ────────────────────────────────────────────────
api.interceptors.request.use((config) => {
  if (import.meta.env.DEV) {
    console.log(`Supabase: ${config.method?.toUpperCase()} ${config.url}`)
  }
  return config
})

// ── Render Backend ────────────────────────────────────────────────────────────
const backendApi = axios.create({
  baseURL: BACKEND_URL,
  timeout: 120000,
  headers: { 'Content-Type': 'application/json' },
})

backendApi.interceptors.request.use((config) => {
  if (import.meta.env.DEV) {
    console.log(`Backend: ${config.method?.toUpperCase()} ${config.url}`)
  }
  return config
})

// ── Response error handlers ───────────────────────────────────────────────────
api.interceptors.response.use(
  res => res,
  async (error) => {
    const status  = error.response?.status
    const message =
      error.response?.data?.error   ||
      error.response?.data?.message ||
      error.message                 ||
      'Something went wrong'

    // ── Auto retry on 429 rate limit ─────────────────────────────────────────
    if (status === 429) {
      const retryAfter = error.response?.headers?.['retry-after']
      const waitMs     = retryAfter ? parseFloat(retryAfter) * 1000 : 2000
      console.warn(`Rate limit hit. Retrying in ${waitMs}ms...`)
      await new Promise(r => setTimeout(r, waitMs))
      try {
        return await api(error.config)
      } catch {
        return Promise.reject(
          new Error('Rate limit exceeded. Please wait a moment and try again.')
        )
      }
    }

    if (import.meta.env.DEV) console.error('Supabase API Error:', message)
    return Promise.reject(new Error(message))
  }
)

backendApi.interceptors.response.use(
  res => res,
  (error) => {
    const message =
      error.response?.data?.detail ||
      error.response?.data?.error  ||
      error.message                ||
      'Video processing failed'
    if (import.meta.env.DEV) console.error('Backend Error:', message)
    return Promise.reject(new Error(message))
  }
)

// ── API Client ────────────────────────────────────────────────────────────────
export const apiClient = {

  // ── Health ───────────────────────────────────────────────────────────────────
  getHealth: () =>
    api.get('/health'),

  // ── Affirmation ───────────────────────────────────────────────────────────────
  // Reads from Supabase DB first (pre-generated by GitHub Actions cron daily)
  // Falls back to Edge Function if no entry exists for today
  getAffirmation: async () => {
    const today = new Date().toISOString().split('T')[0]

    // Method 1: Read directly from Supabase database (instant, no cold start)
    try {
      const { data, error } = await supabase
        .from('daily_affirmations')
        .select('affirmation, date')
        .eq('date', today)
        .single()

      if (!error && data?.affirmation) {
        return { data: { affirmation: data.affirmation } }
      }
    } catch {
      // Silent — try Edge Function next
    }

    // Method 2: Call Edge Function (generates on demand if cron hasn't run yet)
    try {
      const res = await fetch(
        `${FUNCTIONS_URL}/affirmation?action=get`,
        {
          headers: {
            'apikey':        SUPABASE_ANON_KEY,
            'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
          },
        }
      )

      if (res.ok) {
        const json = await res.json()
        if (json.affirmation) {
          return { data: { affirmation: json.affirmation } }
        }
      }
    } catch {
      // Silent — use fallback below
    }

    // Method 3: Hardcoded fallback (always works)
    return {
      data: {
        affirmation: 'You have the analytical mind and the diligence to conquer this exam. One rule, one analysis, one day at a time.',
      },
    }
  },

  // ── Chat ─────────────────────────────────────────────────────────────────────
  chat: (message, history = []) =>
    api.post('/chat', {
      message,
      history,
      model: 'llama-3.1-8b-instant',
    }),

  // ── Ingestion ─────────────────────────────────────────────────────────────────
  ingestUrl: (url) =>
    api.post('/ingest-url', { url }),

  ingestYoutube: (url) =>
    api.post('/ingest-youtube', { url }),

  // ── Mock Exam ─────────────────────────────────────────────────────────────────
  generateQuestion: (topic) =>
    api.post('/mock-exam', { action: 'generate', topic }),

  evaluateAnswer: (question, answer, correct_letter, rationale = '') =>
    api.post('/mock-exam', {
      action: 'evaluate',
      question,
      answer,
      correct_letter,
      rationale,
    }),

  // ── Modules ───────────────────────────────────────────────────────────────────
  getModules: (topic = '', all = false) =>
    api.get(`/get-modules?topic=${encodeURIComponent(topic)}&all=${all}`),

  // ── PDF ───────────────────────────────────────────────────────────────────────
  processPdf: (storage_path, filename, document_id) =>
    api.post('/process-pdf', { storage_path, filename, document_id }),

  // ── Admin Auth ────────────────────────────────────────────────────────────────
  adminLogin: (password) =>
    api.post('/admin-auth', { action: 'login', password }),

  adminVerify: (token) =>
    api.post('/admin-auth', { action: 'verify', password: token }),

  // ── Chat Sessions ─────────────────────────────────────────────────────────────
  getSessions: () =>
    api.get('/chat-sessions'),

  createSession: (title, messages = []) =>
    api.post('/chat-sessions', { action: 'create', title, messages }),

  updateSession: (id, title, messages) =>
    api.post('/chat-sessions', { action: 'update', id, title, messages }),

  getSession: (id) =>
    api.post('/chat-sessions', { action: 'get', id }),

  deleteSession: (id) =>
    api.post('/chat-sessions', { action: 'delete', id }),

  adminGetAllSessions: (adminToken) =>
    api.post('/chat-sessions', {
      action:      'admin_list',
      admin_token: adminToken,
    }),

  // ── Video Processing (Render Backend) ─────────────────────────────────────────
  processVideo: (url, topic, order_index = 0) =>
    backendApi.post('/api/process-video', { url, topic, order_index }),

  // ── Scraper ───────────────────────────────────────────────────────────────────
  triggerScrape: (url, topic = '') =>
    api.post('/scraper', { action: 'scrape', url, topic }),

  getScrapedData: (topic = '', limit = 50) =>
    api.get(
      `/scraper?action=list` +
      `&topic=${encodeURIComponent(topic)}` +
      `&limit=${limit}`
    ),

  deleteScrapedItem: (id) =>
    api.post('/scraper', { action: 'delete', id }),

  syncScrapedToKnowledge: (id) =>
    api.post('/scraper', { action: 'sync', id }),

  // ── Blog ──────────────────────────────────────────────────────────────────────
  getBlogPosts: ({
    page   = 0,
    limit  = 12,
    topic  = '',
    search = '',
  } = {}) =>
    api.get(
      `/blog?action=list` +
      `&page=${page}` +
      `&limit=${limit}` +
      `&topic=${encodeURIComponent(topic)}` +
      `&search=${encodeURIComponent(search)}`
    ),

  getBlogPost: (slug) =>
    api.get(`/blog?action=get&slug=${encodeURIComponent(slug)}`),

  generateBlogPost: ({ topic, source_url = '', custom_prompt = '' }) =>
    api.post('/blog', {
      action: 'generate',
      topic,
      source_url,
      custom_prompt,
    }),

  generateBlogImage: (prompt) =>
    api.post('/blog', { action: 'generate_image', prompt }),

  publishBlogPost: (id) =>
    api.post('/blog', { action: 'publish', id }),

  unpublishBlogPost: (id) =>
    api.post('/blog', { action: 'unpublish', id }),

  deleteBlogPost: (id) =>
    api.post('/blog', { action: 'delete', id }),

  adminGetBlogPosts: (adminToken, status = 'all') =>
    api.post('/blog', {
      action:      'admin_list',
      admin_token: adminToken,
      status,
    }),

  updateBlogPost: (id, updates) =>
    api.post('/blog', { action: 'update', id, ...updates }),

  // ── Newsletter ────────────────────────────────────────────────────────────────
  subscribeNewsletter: (email) =>
    api.post('/newsletter', { email }),

  // ── Stripe Checkout ───────────────────────────────────────────────────────────
  createCheckoutSession: async (priceId, userId, userEmail) => {
    const { data: { session } } = await supabase.auth.getSession()

    const res = await fetch(
      `${FUNCTIONS_URL}/stripe-checkout`,
      {
        method:  'POST',
        headers: {
          'Content-Type':  'application/json',
          'apikey':        SUPABASE_ANON_KEY,
          'Authorization': `Bearer ${session?.access_token || SUPABASE_ANON_KEY}`,
        },
        body: JSON.stringify({
          priceId,
          userId,
          userEmail,
          successUrl: `${window.location.origin}/payment-success`,
          cancelUrl:  `${window.location.origin}/pricing`,
        }),
      }
    )

    if (!res.ok) {
      const err = await res.json()
      throw new Error(err.error || 'Failed to create checkout session')
    }

    return res.json()
  },
}

export default api
